### PR TITLE
Adding support for clang12 and VS2022

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by RubyNova** [comment]
Last I checked NovelRT does not build with Clang 12 due to them importing GCC errors, though this was a recent discovery. Have we confirmed it all works?

**Comment by tannergooding** [comment]
No, but that should be independent of having the profile support, which would allow us to make any necessary changes.

**Comment by RubyNova** [comment]
Fair enough.

**Review by RubyNova — APPROVED** [review]
LGTM

**Pull request merged**
